# Step 1:
#	Set CC to the C compiler you want to use.  On Sun, gcc 
#	produces faster code.  Your mileage may vary.
CC            = gcc
#CC            = cc

# Step 2:
#	Set INCLUDEDIR equal to -I followed by include directory
#	path for X11 include files. 

INCLUDEDIR    = -I/usr/include -I/usr/include/X11

# For Solaris/openwindows
#INCLUDEDIR = -I/usr/include -I/usr/openwin/share/include -I/usr/openwin/include -I/usr/dt/include

#
# Step 3:
#	Set CFLAGS.  Below are def's for some machines.  Uncomment the
#	appropriate one or make one of your own. If you want the player
#       to gather statistics about the video stream, add -DANALYSIS to
#       CFLAGS. If you do NOT want to use shared memory, remove 
#       -DSH_MEM from CFLAGS.
#       Use -DSIG_ONE_PARAM if the function passed to signal takes 
#         one parameter (linux, Solaris)
#         Do not use it if it takes none (SunOS, HPUX, Ultrix, OSF1, )
#         It works either way, (i think), just gets rid of a warning.
#
#       Use -NDEBUG for speed, -DDEBUG for resiliance.  On invalid MPEG
#         streams a DEBUG compiled mpeg_play will exit gracefully, while
#         a NDEBUG one will dump core.  But NDEBUG is faster.

#       Use -DQUIET to have mpeg_play print little by default (useful for
#         when it is called by another program like netscape).

#       Use -DQUALITY if you want the default to play streams that conform
#         strictly to the MPEG standard but take longer to display by defualt.
#         It is also available as -quality on at runtime

#       Use -DFLOATDCT to enable using the computationally expensive but
#         accurate floating point DCT through the -quality parameter.

#       Use -DDEFAULT_ORDERED_DITHER to use ORDERED_DITHER instead of 
#         ORDERED2_DITHER.  On some machines (e.g., Intel Pentiums),
#         ORDERED_DITHER is much faster than ORDERED2_DITHER.
#       Use -DNOCONTROLS to totally disable the X user interface.  See 
#         also HDRS, OBJS, and SRCS below.
#       To compile as a library (especially reentrant library, see README.lib)

# gcc
CFLAGS	      +=  -DNDEBUG -DNONANSI_INCLUDES -DSH_MEM $(INCLUDEDIR) -g

#Sun Solaris/Openwindows 
#CFLAGS = -O3 -DNDEBUG -DBSD -DNONANSI_INCLUDES -DSH_MEM -DSIG_ONE_PARAM $(INCLUDEDIR)

#Linux C Flags
#CFLAGS	      =  -O3 -fomit-frame-pointer -ffast-math -finline-functions -m486 -DNDEBUG -DNONANSI_INCLUDES -DSH_MEM -DSIG_ONE_PARAM $(INCLUDEDIR) -DDEFAULT_ORDERED_DITHER

#HP C Flags 
#CFLAGS        = -Ac +O3 -DSH_MEM -DNDEBUG $(INCLUDEDIR)

#DEC C Flags    (On some Alpha's you need -lbsd also)
#CFLAGS        = -O -DSH_MEM -DNDEBUG $(INCLUDEDIR)

#RS6000 C Flags -- Most RS6000's do not support shared memory,
# but we include it 'cuz it helps so much if you have it.
# by the way, if you want to give us a version of libXext with them, feel free
#CFLAGS        = -O -DSH_MEM $(INCLUDEDIR)

#SGI C Flags
#CFLAGS        = -O -cckr -DSH_MEM $(INCLUDEDIR)

#MIPGS RISC/os 4.5{1,2} C Flags
#CFLAGS        = -O -systype sysv -DSH_MEM -DNONANSI_INCLUDES -DMIPS

#PTX Flags (Dynix)
#CFLAGS        = -O -DNDEBUG $(INCLUDEDIR)

#NEWS C Flags
#CFLAGS	       = -O2 -DSh_MEM -DNO_LRAND48 -DNDEBUG -DNONANSI_INCUDES $(INCLUDEDIR)

#
#NeXT C Flags
#CFLAGS	       = -O -DNO_LRAND48 -DNDEBUG $(INCLUDEDIR)

#CETIA Unigraph/X C Flags
#CFLAGS	       = -O -DNDEBUGS -DBSDCOMPAT -DBSD_LARGE -DCETIA -DX_NOT_STDC_ENV $(INCLUDEDIR) 

# Convex 3820 (ConvexOS)
#CFLAGS	      =  -O3 -DNDEBUG -DNONANSI_INCLUDES $(INCLUDEDIR) -DNO_LRAND48

#
# Step 4:
#	Set LIBS equal to path of libXext.a and libX11.a or the loader
#	flag equivalents (i.e. -lXext -lX11).
#       If you are NOT using shared memory, libXext.a is unecessary.
#       NOTE: below the default definition are
#             a few definitions for specific architectures.

LIBS	      = -L/usr/X11R6/lib -lXext -lX11 /usr/lib/libjpeg.so.62

# LIBS for MIPS RISC/os 4.5{1,2}
#LIBS         = -systype sysv -lXext -lX11 -lbsd

# LIBS for PTX/Dynix
#LIBS         = -lXext -lX11 -lsocket -linet -lnsl -lseq

# LIBS for CETIA Unigraph/X
#LIBS	      = -lX11 -lbsd

# LIBS for Solaris/Openwindows (some also need  -lucb)
#LIBS = -lXext -lX11 -lsocket -lnsl -lw -ldl -lelf

# LIBS for SunOS 4.1.3/Openwindows
#LIBS = -lXext -lX11 -lnsl -ldl


# Some versions of Linux need this
#LIBS	      =  -L/usr/X11/lib -L/usr/lib/X11 -lXext -lX11

#
# Step 5:
#	Set DEST to pathname of final destination of player...
#
DEST	      = /usr/local/bin


#
# Step 6 (System Dependant Stuff):
# On SOLARIS a user reports:
# Some systems are missing regcmp, to fix
# add -lgen to CFLAGS
# Also, uncomment the special SOLARIS INSTALL and LDFLAGS parameters.

#
# That's it!  The rest of this shouldn't need any modifications...
#

EXTHDRS	      =

HDRS	      = util.h video.h decoders.h fs2.h dither.h fs4.h ctrlbar.h

INSTALL	      = install

#Solaris INSTALL
#INSTALL       = /usr/sbin/install

LD            = $(CC)

LDFLAGS       =

#Solaris LDFLAGS
#LDFLAGS       = -R/usr/openwin/lib:/usr/dt/lib -L/usr/openwin/lib -L/usr/dt/lib


MAKEFILE      = Makefile

OBJS          = util.o video.o parseblock.o motionvector.o decoders.o \
                fs2.o fs2fast.o fs4.o hybrid.o hybriderr.o 2x2.o floatdct.o\
                gdith.o gray.o mono.o main.o jrevdct.o 16bit.o util32.o\
                ordered.o ordered2.o mb_ordered.o readfile.o ctrlbar.o 

PRINT	      = pr

PROGRAM       = mpeg_play

SHELL	      = /bin/sh

SRCS	      = util.c video.c parseblock.c motionvector.c decoders.c \
                main.c gdith.c fs2.c fs2fast.c fs4.c hybrid.c hybriderr.c \
                2x2.c gray.c mono.c jrevdct.c 16bit.c util32.c ordered.c \
                ordered2.c mb_ordered.c readfile.c floatdct.c ctrlbar.c 

SYSHDRS	      = 

all:		$(PROGRAM)

$(PROGRAM):	$(OBJS)
		$(LD) $(LDFLAGS) $(OBJS) $(LIBS) -lm -o $(PROGRAM)

clean:;		rm -f $(OBJS) core mpeg_play mpeg-loop
		@make depend

clobber:;	rm -f $(OBJS) $(PROGRAM) core tags

depend:;	makedepend -MM $(SRCS) > /tmp/foo

echo:;		@echo $(HDRS) $(SRCS)

index:;		@ctags -wx $(HDRS) $(SRCS)

install:	$(PROGRAM)
		@echo Installing $(PROGRAM) in $(DEST)
		@-strip $(PROGRAM)
		@if [ $(DEST) != . ]; then \
		(rm -f $(DEST)/$(PROGRAM); $(INSTALL) $(PROGRAM) $(DEST)/mpeg-loop); fi

print:;		@$(PRINT) $(HDRS) $(SRCS)

tags:           $(HDRS) $(SRCS); @ctags $(HDRS) $(SRCS)

update:		$(DEST)/$(PROGRAM)

# DO NOT DELETE THIS LINE -- make depend depends on it.

util.o: /usr/include/stdlib.h /usr/include/features.h
util.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
util.o: /usr/lib/gcc-lib/i386-redhat-linux/egcs-2.91.66/include/stddef.h
util.o: /usr/include/sys/types.h /usr/include/bits/types.h
util.o: /usr/include/time.h /usr/include/endian.h /usr/include/bits/endian.h
util.o: /usr/include/sys/select.h /usr/include/bits/select.h
util.o: /usr/include/bits/sigset.h /usr/include/sys/sysmacros.h
util.o: /usr/include/alloca.h video.h /usr/include/stdio.h
util.o: /usr/lib/gcc-lib/i386-redhat-linux/egcs-2.91.66/include/stdarg.h
util.o: /usr/include/libio.h /usr/include/_G_config.h
util.o: /usr/include/bits/stdio_lim.h /usr/include/X11/Xlib.h
util.o: /usr/include/X11/X.h /usr/include/X11/Xfuncproto.h
util.o: /usr/include/X11/Xosdefs.h /usr/include/X11/Xutil.h vroot.h
util.o: /usr/include/X11/Xatom.h /usr/include/sys/ipc.h
util.o: /usr/include/bits/ipc.h /usr/include/sys/shm.h /usr/include/unistd.h
util.o: /usr/include/bits/posix_opt.h /usr/include/bits/confname.h
util.o: /usr/include/getopt.h /usr/include/bits/shm.h
util.o: /usr/include/X11/extensions/XShm.h proto.h util.h ctrlbar.h
video.o: /usr/include/stdio.h /usr/include/features.h
video.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
video.o: /usr/lib/gcc-lib/i386-redhat-linux/egcs-2.91.66/include/stddef.h
video.o: /usr/lib/gcc-lib/i386-redhat-linux/egcs-2.91.66/include/stdarg.h
video.o: /usr/include/bits/types.h /usr/include/libio.h
video.o: /usr/include/_G_config.h /usr/include/bits/stdio_lim.h
video.o: /usr/include/stdlib.h /usr/include/sys/types.h /usr/include/time.h
video.o: /usr/include/endian.h /usr/include/bits/endian.h
video.o: /usr/include/sys/select.h /usr/include/bits/select.h
video.o: /usr/include/bits/sigset.h /usr/include/sys/sysmacros.h
video.o: /usr/include/alloca.h /usr/include/assert.h /usr/include/sys/time.h
video.o: /usr/include/bits/time.h ctrlbar.h /usr/include/X11/Xlib.h
video.o: /usr/include/X11/X.h /usr/include/X11/Xfuncproto.h
video.o: /usr/include/X11/Xosdefs.h /usr/include/X11/Xutil.h decoders.h
video.o: util.h video.h vroot.h /usr/include/X11/Xatom.h
video.o: /usr/include/sys/ipc.h /usr/include/bits/ipc.h
video.o: /usr/include/sys/shm.h /usr/include/unistd.h
video.o: /usr/include/bits/posix_opt.h /usr/include/bits/confname.h
video.o: /usr/include/getopt.h /usr/include/bits/shm.h
video.o: /usr/include/X11/extensions/XShm.h proto.h
parseblock.o: /usr/include/assert.h /usr/include/features.h
parseblock.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h video.h
parseblock.o: /usr/include/stdio.h
parseblock.o: /usr/lib/gcc-lib/i386-redhat-linux/egcs-2.91.66/include/stddef.h
parseblock.o: /usr/lib/gcc-lib/i386-redhat-linux/egcs-2.91.66/include/stdarg.h
parseblock.o: /usr/include/bits/types.h /usr/include/libio.h
parseblock.o: /usr/include/_G_config.h /usr/include/bits/stdio_lim.h
parseblock.o: /usr/include/X11/Xlib.h /usr/include/sys/types.h
parseblock.o: /usr/include/time.h /usr/include/endian.h
parseblock.o: /usr/include/bits/endian.h /usr/include/sys/select.h
parseblock.o: /usr/include/bits/select.h /usr/include/bits/sigset.h
parseblock.o: /usr/include/sys/sysmacros.h /usr/include/X11/X.h
parseblock.o: /usr/include/X11/Xfuncproto.h /usr/include/X11/Xosdefs.h
parseblock.o: /usr/include/X11/Xutil.h vroot.h /usr/include/X11/Xatom.h
parseblock.o: /usr/include/sys/ipc.h /usr/include/bits/ipc.h
parseblock.o: /usr/include/sys/shm.h /usr/include/unistd.h
parseblock.o: /usr/include/bits/posix_opt.h /usr/include/bits/confname.h
parseblock.o: /usr/include/getopt.h /usr/include/bits/shm.h
parseblock.o: /usr/include/X11/extensions/XShm.h proto.h
parseblock.o: /usr/include/stdlib.h /usr/include/alloca.h decoders.h util.h
motionvector.o: video.h /usr/include/stdio.h /usr/include/features.h
motionvector.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
motionvector.o: /usr/lib/gcc-lib/i386-redhat-linux/egcs-2.91.66/include/stddef.h
motionvector.o: /usr/lib/gcc-lib/i386-redhat-linux/egcs-2.91.66/include/stdarg.h
motionvector.o: /usr/include/bits/types.h /usr/include/libio.h
motionvector.o: /usr/include/_G_config.h /usr/include/bits/stdio_lim.h
motionvector.o: /usr/include/X11/Xlib.h /usr/include/sys/types.h
motionvector.o: /usr/include/time.h /usr/include/endian.h
motionvector.o: /usr/include/bits/endian.h /usr/include/sys/select.h
motionvector.o: /usr/include/bits/select.h /usr/include/bits/sigset.h
motionvector.o: /usr/include/sys/sysmacros.h /usr/include/X11/X.h
motionvector.o: /usr/include/X11/Xfuncproto.h /usr/include/X11/Xosdefs.h
motionvector.o: /usr/include/X11/Xutil.h vroot.h /usr/include/X11/Xatom.h
motionvector.o: /usr/include/sys/ipc.h /usr/include/bits/ipc.h
motionvector.o: /usr/include/sys/shm.h /usr/include/unistd.h
motionvector.o: /usr/include/bits/posix_opt.h /usr/include/bits/confname.h
motionvector.o: /usr/include/getopt.h /usr/include/bits/shm.h
motionvector.o: /usr/include/X11/extensions/XShm.h proto.h
motionvector.o: /usr/include/stdlib.h /usr/include/alloca.h util.h
decoders.o: /usr/include/stdio.h /usr/include/features.h
decoders.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
decoders.o: /usr/lib/gcc-lib/i386-redhat-linux/egcs-2.91.66/include/stddef.h
decoders.o: /usr/lib/gcc-lib/i386-redhat-linux/egcs-2.91.66/include/stdarg.h
decoders.o: /usr/include/bits/types.h /usr/include/libio.h
decoders.o: /usr/include/_G_config.h /usr/include/bits/stdio_lim.h
decoders.o: /usr/include/assert.h decoders.h util.h video.h
decoders.o: /usr/include/X11/Xlib.h /usr/include/sys/types.h
decoders.o: /usr/include/time.h /usr/include/endian.h
decoders.o: /usr/include/bits/endian.h /usr/include/sys/select.h
decoders.o: /usr/include/bits/select.h /usr/include/bits/sigset.h
decoders.o: /usr/include/sys/sysmacros.h /usr/include/X11/X.h
decoders.o: /usr/include/X11/Xfuncproto.h /usr/include/X11/Xosdefs.h
decoders.o: /usr/include/X11/Xutil.h vroot.h /usr/include/X11/Xatom.h
decoders.o: /usr/include/sys/ipc.h /usr/include/bits/ipc.h
decoders.o: /usr/include/sys/shm.h /usr/include/unistd.h
decoders.o: /usr/include/bits/posix_opt.h /usr/include/bits/confname.h
decoders.o: /usr/include/getopt.h /usr/include/bits/shm.h
decoders.o: /usr/include/X11/extensions/XShm.h proto.h /usr/include/stdlib.h
decoders.o: /usr/include/alloca.h
main.o: video.h /usr/include/stdio.h /usr/include/features.h
main.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
main.o: /usr/lib/gcc-lib/i386-redhat-linux/egcs-2.91.66/include/stddef.h
main.o: /usr/lib/gcc-lib/i386-redhat-linux/egcs-2.91.66/include/stdarg.h
main.o: /usr/include/bits/types.h /usr/include/libio.h
main.o: /usr/include/_G_config.h /usr/include/bits/stdio_lim.h
main.o: /usr/include/X11/Xlib.h /usr/include/sys/types.h /usr/include/time.h
main.o: /usr/include/endian.h /usr/include/bits/endian.h
main.o: /usr/include/sys/select.h /usr/include/bits/select.h
main.o: /usr/include/bits/sigset.h /usr/include/sys/sysmacros.h
main.o: /usr/include/X11/X.h /usr/include/X11/Xfuncproto.h
main.o: /usr/include/X11/Xosdefs.h /usr/include/X11/Xutil.h vroot.h
main.o: /usr/include/X11/Xatom.h /usr/include/sys/ipc.h
main.o: /usr/include/bits/ipc.h /usr/include/sys/shm.h /usr/include/unistd.h
main.o: /usr/include/bits/posix_opt.h /usr/include/bits/confname.h
main.o: /usr/include/getopt.h /usr/include/bits/shm.h
main.o: /usr/include/X11/extensions/XShm.h proto.h /usr/include/stdlib.h
main.o: /usr/include/alloca.h ctrlbar.h /usr/include/math.h
main.o: /usr/include/bits/huge_val.h /usr/include/bits/mathdef.h
main.o: /usr/include/bits/mathcalls.h
main.o: /usr/lib/gcc-lib/i386-redhat-linux/egcs-2.91.66/include/float.h
main.o: /usr/include/signal.h /usr/include/bits/signum.h
main.o: /usr/include/bits/siginfo.h /usr/include/bits/sigaction.h
main.o: /usr/include/bits/sigcontext.h /usr/include/asm/sigcontext.h
main.o: /usr/include/bits/sigstack.h /usr/include/netinet/in.h
main.o: /usr/include/stdint.h /usr/include/bits/socket.h
main.o: /usr/include/bits/sockaddr.h /usr/include/asm/socket.h
main.o: /usr/include/asm/sockios.h /usr/include/bits/in.h
main.o: /usr/include/bits/byteswap.h /usr/include/string.h util.h dither.h
gdith.o: /usr/include/math.h /usr/include/features.h /usr/include/sys/cdefs.h
gdith.o: /usr/include/gnu/stubs.h /usr/include/bits/huge_val.h
gdith.o: /usr/include/bits/mathdef.h /usr/include/bits/mathcalls.h
gdith.o: /usr/lib/gcc-lib/i386-redhat-linux/egcs-2.91.66/include/float.h
gdith.o: video.h /usr/include/stdio.h
gdith.o: /usr/lib/gcc-lib/i386-redhat-linux/egcs-2.91.66/include/stddef.h
gdith.o: /usr/lib/gcc-lib/i386-redhat-linux/egcs-2.91.66/include/stdarg.h
gdith.o: /usr/include/bits/types.h /usr/include/libio.h
gdith.o: /usr/include/_G_config.h /usr/include/bits/stdio_lim.h
gdith.o: /usr/include/X11/Xlib.h /usr/include/sys/types.h /usr/include/time.h
gdith.o: /usr/include/endian.h /usr/include/bits/endian.h
gdith.o: /usr/include/sys/select.h /usr/include/bits/select.h
gdith.o: /usr/include/bits/sigset.h /usr/include/sys/sysmacros.h
gdith.o: /usr/include/X11/X.h /usr/include/X11/Xfuncproto.h
gdith.o: /usr/include/X11/Xosdefs.h /usr/include/X11/Xutil.h vroot.h
gdith.o: /usr/include/X11/Xatom.h /usr/include/sys/ipc.h
gdith.o: /usr/include/bits/ipc.h /usr/include/sys/shm.h /usr/include/unistd.h
gdith.o: /usr/include/bits/posix_opt.h /usr/include/bits/confname.h
gdith.o: /usr/include/getopt.h /usr/include/bits/shm.h
gdith.o: /usr/include/X11/extensions/XShm.h proto.h /usr/include/stdlib.h
gdith.o: /usr/include/alloca.h dither.h ctrlbar.h /usr/include/sys/time.h
gdith.o: /usr/include/bits/time.h /usr/include/string.h
fs2.o: video.h /usr/include/stdio.h /usr/include/features.h
fs2.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
fs2.o: /usr/lib/gcc-lib/i386-redhat-linux/egcs-2.91.66/include/stddef.h
fs2.o: /usr/lib/gcc-lib/i386-redhat-linux/egcs-2.91.66/include/stdarg.h
fs2.o: /usr/include/bits/types.h /usr/include/libio.h
fs2.o: /usr/include/_G_config.h /usr/include/bits/stdio_lim.h
fs2.o: /usr/include/X11/Xlib.h /usr/include/sys/types.h /usr/include/time.h
fs2.o: /usr/include/endian.h /usr/include/bits/endian.h
fs2.o: /usr/include/sys/select.h /usr/include/bits/select.h
fs2.o: /usr/include/bits/sigset.h /usr/include/sys/sysmacros.h
fs2.o: /usr/include/X11/X.h /usr/include/X11/Xfuncproto.h
fs2.o: /usr/include/X11/Xosdefs.h /usr/include/X11/Xutil.h vroot.h
fs2.o: /usr/include/X11/Xatom.h /usr/include/sys/ipc.h
fs2.o: /usr/include/bits/ipc.h /usr/include/sys/shm.h /usr/include/unistd.h
fs2.o: /usr/include/bits/posix_opt.h /usr/include/bits/confname.h
fs2.o: /usr/include/getopt.h /usr/include/bits/shm.h
fs2.o: /usr/include/X11/extensions/XShm.h dither.h fs2.h proto.h
fs2.o: /usr/include/stdlib.h /usr/include/alloca.h
fs2fast.o: video.h /usr/include/stdio.h /usr/include/features.h
fs2fast.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
fs2fast.o: /usr/lib/gcc-lib/i386-redhat-linux/egcs-2.91.66/include/stddef.h
fs2fast.o: /usr/lib/gcc-lib/i386-redhat-linux/egcs-2.91.66/include/stdarg.h
fs2fast.o: /usr/include/bits/types.h /usr/include/libio.h
fs2fast.o: /usr/include/_G_config.h /usr/include/bits/stdio_lim.h
fs2fast.o: /usr/include/X11/Xlib.h /usr/include/sys/types.h
fs2fast.o: /usr/include/time.h /usr/include/endian.h
fs2fast.o: /usr/include/bits/endian.h /usr/include/sys/select.h
fs2fast.o: /usr/include/bits/select.h /usr/include/bits/sigset.h
fs2fast.o: /usr/include/sys/sysmacros.h /usr/include/X11/X.h
fs2fast.o: /usr/include/X11/Xfuncproto.h /usr/include/X11/Xosdefs.h
fs2fast.o: /usr/include/X11/Xutil.h vroot.h /usr/include/X11/Xatom.h
fs2fast.o: /usr/include/sys/ipc.h /usr/include/bits/ipc.h
fs2fast.o: /usr/include/sys/shm.h /usr/include/unistd.h
fs2fast.o: /usr/include/bits/posix_opt.h /usr/include/bits/confname.h
fs2fast.o: /usr/include/getopt.h /usr/include/bits/shm.h
fs2fast.o: /usr/include/X11/extensions/XShm.h proto.h /usr/include/stdlib.h
fs2fast.o: /usr/include/alloca.h dither.h
fs4.o: fs4.h video.h /usr/include/stdio.h /usr/include/features.h
fs4.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
fs4.o: /usr/lib/gcc-lib/i386-redhat-linux/egcs-2.91.66/include/stddef.h
fs4.o: /usr/lib/gcc-lib/i386-redhat-linux/egcs-2.91.66/include/stdarg.h
fs4.o: /usr/include/bits/types.h /usr/include/libio.h
fs4.o: /usr/include/_G_config.h /usr/include/bits/stdio_lim.h
fs4.o: /usr/include/X11/Xlib.h /usr/include/sys/types.h /usr/include/time.h
fs4.o: /usr/include/endian.h /usr/include/bits/endian.h
fs4.o: /usr/include/sys/select.h /usr/include/bits/select.h
fs4.o: /usr/include/bits/sigset.h /usr/include/sys/sysmacros.h
fs4.o: /usr/include/X11/X.h /usr/include/X11/Xfuncproto.h
fs4.o: /usr/include/X11/Xosdefs.h /usr/include/X11/Xutil.h vroot.h
fs4.o: /usr/include/X11/Xatom.h /usr/include/sys/ipc.h
fs4.o: /usr/include/bits/ipc.h /usr/include/sys/shm.h /usr/include/unistd.h
fs4.o: /usr/include/bits/posix_opt.h /usr/include/bits/confname.h
fs4.o: /usr/include/getopt.h /usr/include/bits/shm.h
fs4.o: /usr/include/X11/extensions/XShm.h proto.h /usr/include/stdlib.h
fs4.o: /usr/include/alloca.h dither.h
hybrid.o: video.h /usr/include/stdio.h /usr/include/features.h
hybrid.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
hybrid.o: /usr/lib/gcc-lib/i386-redhat-linux/egcs-2.91.66/include/stddef.h
hybrid.o: /usr/lib/gcc-lib/i386-redhat-linux/egcs-2.91.66/include/stdarg.h
hybrid.o: /usr/include/bits/types.h /usr/include/libio.h
hybrid.o: /usr/include/_G_config.h /usr/include/bits/stdio_lim.h
hybrid.o: /usr/include/X11/Xlib.h /usr/include/sys/types.h
hybrid.o: /usr/include/time.h /usr/include/endian.h
hybrid.o: /usr/include/bits/endian.h /usr/include/sys/select.h
hybrid.o: /usr/include/bits/select.h /usr/include/bits/sigset.h
hybrid.o: /usr/include/sys/sysmacros.h /usr/include/X11/X.h
hybrid.o: /usr/include/X11/Xfuncproto.h /usr/include/X11/Xosdefs.h
hybrid.o: /usr/include/X11/Xutil.h vroot.h /usr/include/X11/Xatom.h
hybrid.o: /usr/include/sys/ipc.h /usr/include/bits/ipc.h
hybrid.o: /usr/include/sys/shm.h /usr/include/unistd.h
hybrid.o: /usr/include/bits/posix_opt.h /usr/include/bits/confname.h
hybrid.o: /usr/include/getopt.h /usr/include/bits/shm.h
hybrid.o: /usr/include/X11/extensions/XShm.h proto.h /usr/include/stdlib.h
hybrid.o: /usr/include/alloca.h dither.h
hybriderr.o: video.h /usr/include/stdio.h /usr/include/features.h
hybriderr.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
hybriderr.o: /usr/lib/gcc-lib/i386-redhat-linux/egcs-2.91.66/include/stddef.h
hybriderr.o: /usr/lib/gcc-lib/i386-redhat-linux/egcs-2.91.66/include/stdarg.h
hybriderr.o: /usr/include/bits/types.h /usr/include/libio.h
hybriderr.o: /usr/include/_G_config.h /usr/include/bits/stdio_lim.h
hybriderr.o: /usr/include/X11/Xlib.h /usr/include/sys/types.h
hybriderr.o: /usr/include/time.h /usr/include/endian.h
hybriderr.o: /usr/include/bits/endian.h /usr/include/sys/select.h
hybriderr.o: /usr/include/bits/select.h /usr/include/bits/sigset.h
hybriderr.o: /usr/include/sys/sysmacros.h /usr/include/X11/X.h
hybriderr.o: /usr/include/X11/Xfuncproto.h /usr/include/X11/Xosdefs.h
hybriderr.o: /usr/include/X11/Xutil.h vroot.h /usr/include/X11/Xatom.h
hybriderr.o: /usr/include/sys/ipc.h /usr/include/bits/ipc.h
hybriderr.o: /usr/include/sys/shm.h /usr/include/unistd.h
hybriderr.o: /usr/include/bits/posix_opt.h /usr/include/bits/confname.h
hybriderr.o: /usr/include/getopt.h /usr/include/bits/shm.h
hybriderr.o: /usr/include/X11/extensions/XShm.h proto.h /usr/include/stdlib.h
hybriderr.o: /usr/include/alloca.h dither.h
2x2.o: video.h /usr/include/stdio.h /usr/include/features.h
2x2.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
2x2.o: /usr/lib/gcc-lib/i386-redhat-linux/egcs-2.91.66/include/stddef.h
2x2.o: /usr/lib/gcc-lib/i386-redhat-linux/egcs-2.91.66/include/stdarg.h
2x2.o: /usr/include/bits/types.h /usr/include/libio.h
2x2.o: /usr/include/_G_config.h /usr/include/bits/stdio_lim.h
2x2.o: /usr/include/X11/Xlib.h /usr/include/sys/types.h /usr/include/time.h
2x2.o: /usr/include/endian.h /usr/include/bits/endian.h
2x2.o: /usr/include/sys/select.h /usr/include/bits/select.h
2x2.o: /usr/include/bits/sigset.h /usr/include/sys/sysmacros.h
2x2.o: /usr/include/X11/X.h /usr/include/X11/Xfuncproto.h
2x2.o: /usr/include/X11/Xosdefs.h /usr/include/X11/Xutil.h vroot.h
2x2.o: /usr/include/X11/Xatom.h /usr/include/sys/ipc.h
2x2.o: /usr/include/bits/ipc.h /usr/include/sys/shm.h /usr/include/unistd.h
2x2.o: /usr/include/bits/posix_opt.h /usr/include/bits/confname.h
2x2.o: /usr/include/getopt.h /usr/include/bits/shm.h
2x2.o: /usr/include/X11/extensions/XShm.h dither.h proto.h
2x2.o: /usr/include/stdlib.h /usr/include/alloca.h
gray.o: video.h /usr/include/stdio.h /usr/include/features.h
gray.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
gray.o: /usr/lib/gcc-lib/i386-redhat-linux/egcs-2.91.66/include/stddef.h
gray.o: /usr/lib/gcc-lib/i386-redhat-linux/egcs-2.91.66/include/stdarg.h
gray.o: /usr/include/bits/types.h /usr/include/libio.h
gray.o: /usr/include/_G_config.h /usr/include/bits/stdio_lim.h
gray.o: /usr/include/X11/Xlib.h /usr/include/sys/types.h /usr/include/time.h
gray.o: /usr/include/endian.h /usr/include/bits/endian.h
gray.o: /usr/include/sys/select.h /usr/include/bits/select.h
gray.o: /usr/include/bits/sigset.h /usr/include/sys/sysmacros.h
gray.o: /usr/include/X11/X.h /usr/include/X11/Xfuncproto.h
gray.o: /usr/include/X11/Xosdefs.h /usr/include/X11/Xutil.h vroot.h
gray.o: /usr/include/X11/Xatom.h /usr/include/sys/ipc.h
gray.o: /usr/include/bits/ipc.h /usr/include/sys/shm.h /usr/include/unistd.h
gray.o: /usr/include/bits/posix_opt.h /usr/include/bits/confname.h
gray.o: /usr/include/getopt.h /usr/include/bits/shm.h
gray.o: /usr/include/X11/extensions/XShm.h proto.h /usr/include/stdlib.h
gray.o: /usr/include/alloca.h dither.h
mono.o: video.h /usr/include/stdio.h /usr/include/features.h
mono.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
mono.o: /usr/lib/gcc-lib/i386-redhat-linux/egcs-2.91.66/include/stddef.h
mono.o: /usr/lib/gcc-lib/i386-redhat-linux/egcs-2.91.66/include/stdarg.h
mono.o: /usr/include/bits/types.h /usr/include/libio.h
mono.o: /usr/include/_G_config.h /usr/include/bits/stdio_lim.h
mono.o: /usr/include/X11/Xlib.h /usr/include/sys/types.h /usr/include/time.h
mono.o: /usr/include/endian.h /usr/include/bits/endian.h
mono.o: /usr/include/sys/select.h /usr/include/bits/select.h
mono.o: /usr/include/bits/sigset.h /usr/include/sys/sysmacros.h
mono.o: /usr/include/X11/X.h /usr/include/X11/Xfuncproto.h
mono.o: /usr/include/X11/Xosdefs.h /usr/include/X11/Xutil.h vroot.h
mono.o: /usr/include/X11/Xatom.h /usr/include/sys/ipc.h
mono.o: /usr/include/bits/ipc.h /usr/include/sys/shm.h /usr/include/unistd.h
mono.o: /usr/include/bits/posix_opt.h /usr/include/bits/confname.h
mono.o: /usr/include/getopt.h /usr/include/bits/shm.h
mono.o: /usr/include/X11/extensions/XShm.h proto.h /usr/include/stdlib.h
mono.o: /usr/include/alloca.h dither.h
jrevdct.o: /usr/include/string.h /usr/include/features.h
jrevdct.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
jrevdct.o: /usr/lib/gcc-lib/i386-redhat-linux/egcs-2.91.66/include/stddef.h
jrevdct.o: video.h /usr/include/stdio.h
jrevdct.o: /usr/lib/gcc-lib/i386-redhat-linux/egcs-2.91.66/include/stdarg.h
jrevdct.o: /usr/include/bits/types.h /usr/include/libio.h
jrevdct.o: /usr/include/_G_config.h /usr/include/bits/stdio_lim.h
jrevdct.o: /usr/include/X11/Xlib.h /usr/include/sys/types.h
jrevdct.o: /usr/include/time.h /usr/include/endian.h
jrevdct.o: /usr/include/bits/endian.h /usr/include/sys/select.h
jrevdct.o: /usr/include/bits/select.h /usr/include/bits/sigset.h
jrevdct.o: /usr/include/sys/sysmacros.h /usr/include/X11/X.h
jrevdct.o: /usr/include/X11/Xfuncproto.h /usr/include/X11/Xosdefs.h
jrevdct.o: /usr/include/X11/Xutil.h vroot.h /usr/include/X11/Xatom.h
jrevdct.o: /usr/include/sys/ipc.h /usr/include/bits/ipc.h
jrevdct.o: /usr/include/sys/shm.h /usr/include/unistd.h
jrevdct.o: /usr/include/bits/posix_opt.h /usr/include/bits/confname.h
jrevdct.o: /usr/include/getopt.h /usr/include/bits/shm.h
jrevdct.o: /usr/include/X11/extensions/XShm.h proto.h /usr/include/stdlib.h
jrevdct.o: /usr/include/alloca.h
16bit.o: video.h /usr/include/stdio.h /usr/include/features.h
16bit.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
16bit.o: /usr/lib/gcc-lib/i386-redhat-linux/egcs-2.91.66/include/stddef.h
16bit.o: /usr/lib/gcc-lib/i386-redhat-linux/egcs-2.91.66/include/stdarg.h
16bit.o: /usr/include/bits/types.h /usr/include/libio.h
16bit.o: /usr/include/_G_config.h /usr/include/bits/stdio_lim.h
16bit.o: /usr/include/X11/Xlib.h /usr/include/sys/types.h /usr/include/time.h
16bit.o: /usr/include/endian.h /usr/include/bits/endian.h
16bit.o: /usr/include/sys/select.h /usr/include/bits/select.h
16bit.o: /usr/include/bits/sigset.h /usr/include/sys/sysmacros.h
16bit.o: /usr/include/X11/X.h /usr/include/X11/Xfuncproto.h
16bit.o: /usr/include/X11/Xosdefs.h /usr/include/X11/Xutil.h vroot.h
16bit.o: /usr/include/X11/Xatom.h /usr/include/sys/ipc.h
16bit.o: /usr/include/bits/ipc.h /usr/include/sys/shm.h /usr/include/unistd.h
16bit.o: /usr/include/bits/posix_opt.h /usr/include/bits/confname.h
16bit.o: /usr/include/getopt.h /usr/include/bits/shm.h
16bit.o: /usr/include/X11/extensions/XShm.h dither.h proto.h
16bit.o: /usr/include/stdlib.h /usr/include/alloca.h /usr/include/math.h
16bit.o: /usr/include/bits/huge_val.h /usr/include/bits/mathdef.h
16bit.o: /usr/include/bits/mathcalls.h
16bit.o: /usr/lib/gcc-lib/i386-redhat-linux/egcs-2.91.66/include/float.h
util32.o: /usr/include/stdio.h /usr/include/features.h
util32.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
util32.o: /usr/lib/gcc-lib/i386-redhat-linux/egcs-2.91.66/include/stddef.h
util32.o: /usr/lib/gcc-lib/i386-redhat-linux/egcs-2.91.66/include/stdarg.h
util32.o: /usr/include/bits/types.h /usr/include/libio.h
util32.o: /usr/include/_G_config.h /usr/include/bits/stdio_lim.h
util32.o: /usr/include/X11/Xlib.h /usr/include/sys/types.h
util32.o: /usr/include/time.h /usr/include/endian.h
util32.o: /usr/include/bits/endian.h /usr/include/sys/select.h
util32.o: /usr/include/bits/select.h /usr/include/bits/sigset.h
util32.o: /usr/include/sys/sysmacros.h /usr/include/X11/X.h
util32.o: /usr/include/X11/Xfuncproto.h /usr/include/X11/Xosdefs.h
util32.o: /usr/include/X11/Xutil.h video.h vroot.h /usr/include/X11/Xatom.h
util32.o: /usr/include/sys/ipc.h /usr/include/bits/ipc.h
util32.o: /usr/include/sys/shm.h /usr/include/unistd.h
util32.o: /usr/include/bits/posix_opt.h /usr/include/bits/confname.h
util32.o: /usr/include/getopt.h /usr/include/bits/shm.h
util32.o: /usr/include/X11/extensions/XShm.h proto.h /usr/include/stdlib.h
util32.o: /usr/include/alloca.h
ordered.o: video.h /usr/include/stdio.h /usr/include/features.h
ordered.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
ordered.o: /usr/lib/gcc-lib/i386-redhat-linux/egcs-2.91.66/include/stddef.h
ordered.o: /usr/lib/gcc-lib/i386-redhat-linux/egcs-2.91.66/include/stdarg.h
ordered.o: /usr/include/bits/types.h /usr/include/libio.h
ordered.o: /usr/include/_G_config.h /usr/include/bits/stdio_lim.h
ordered.o: /usr/include/X11/Xlib.h /usr/include/sys/types.h
ordered.o: /usr/include/time.h /usr/include/endian.h
ordered.o: /usr/include/bits/endian.h /usr/include/sys/select.h
ordered.o: /usr/include/bits/select.h /usr/include/bits/sigset.h
ordered.o: /usr/include/sys/sysmacros.h /usr/include/X11/X.h
ordered.o: /usr/include/X11/Xfuncproto.h /usr/include/X11/Xosdefs.h
ordered.o: /usr/include/X11/Xutil.h vroot.h /usr/include/X11/Xatom.h
ordered.o: /usr/include/sys/ipc.h /usr/include/bits/ipc.h
ordered.o: /usr/include/sys/shm.h /usr/include/unistd.h
ordered.o: /usr/include/bits/posix_opt.h /usr/include/bits/confname.h
ordered.o: /usr/include/getopt.h /usr/include/bits/shm.h
ordered.o: /usr/include/X11/extensions/XShm.h proto.h /usr/include/stdlib.h
ordered.o: /usr/include/alloca.h dither.h
ordered2.o: video.h /usr/include/stdio.h /usr/include/features.h
ordered2.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
ordered2.o: /usr/lib/gcc-lib/i386-redhat-linux/egcs-2.91.66/include/stddef.h
ordered2.o: /usr/lib/gcc-lib/i386-redhat-linux/egcs-2.91.66/include/stdarg.h
ordered2.o: /usr/include/bits/types.h /usr/include/libio.h
ordered2.o: /usr/include/_G_config.h /usr/include/bits/stdio_lim.h
ordered2.o: /usr/include/X11/Xlib.h /usr/include/sys/types.h
ordered2.o: /usr/include/time.h /usr/include/endian.h
ordered2.o: /usr/include/bits/endian.h /usr/include/sys/select.h
ordered2.o: /usr/include/bits/select.h /usr/include/bits/sigset.h
ordered2.o: /usr/include/sys/sysmacros.h /usr/include/X11/X.h
ordered2.o: /usr/include/X11/Xfuncproto.h /usr/include/X11/Xosdefs.h
ordered2.o: /usr/include/X11/Xutil.h vroot.h /usr/include/X11/Xatom.h
ordered2.o: /usr/include/sys/ipc.h /usr/include/bits/ipc.h
ordered2.o: /usr/include/sys/shm.h /usr/include/unistd.h
ordered2.o: /usr/include/bits/posix_opt.h /usr/include/bits/confname.h
ordered2.o: /usr/include/getopt.h /usr/include/bits/shm.h
ordered2.o: /usr/include/X11/extensions/XShm.h proto.h /usr/include/stdlib.h
ordered2.o: /usr/include/alloca.h dither.h
mb_ordered.o: video.h /usr/include/stdio.h /usr/include/features.h
mb_ordered.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
mb_ordered.o: /usr/lib/gcc-lib/i386-redhat-linux/egcs-2.91.66/include/stddef.h
mb_ordered.o: /usr/lib/gcc-lib/i386-redhat-linux/egcs-2.91.66/include/stdarg.h
mb_ordered.o: /usr/include/bits/types.h /usr/include/libio.h
mb_ordered.o: /usr/include/_G_config.h /usr/include/bits/stdio_lim.h
mb_ordered.o: /usr/include/X11/Xlib.h /usr/include/sys/types.h
mb_ordered.o: /usr/include/time.h /usr/include/endian.h
mb_ordered.o: /usr/include/bits/endian.h /usr/include/sys/select.h
mb_ordered.o: /usr/include/bits/select.h /usr/include/bits/sigset.h
mb_ordered.o: /usr/include/sys/sysmacros.h /usr/include/X11/X.h
mb_ordered.o: /usr/include/X11/Xfuncproto.h /usr/include/X11/Xosdefs.h
mb_ordered.o: /usr/include/X11/Xutil.h vroot.h /usr/include/X11/Xatom.h
mb_ordered.o: /usr/include/sys/ipc.h /usr/include/bits/ipc.h
mb_ordered.o: /usr/include/sys/shm.h /usr/include/unistd.h
mb_ordered.o: /usr/include/bits/posix_opt.h /usr/include/bits/confname.h
mb_ordered.o: /usr/include/getopt.h /usr/include/bits/shm.h
mb_ordered.o: /usr/include/X11/extensions/XShm.h proto.h
mb_ordered.o: /usr/include/stdlib.h /usr/include/alloca.h dither.h
readfile.o: video.h /usr/include/stdio.h /usr/include/features.h
readfile.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
readfile.o: /usr/lib/gcc-lib/i386-redhat-linux/egcs-2.91.66/include/stddef.h
readfile.o: /usr/lib/gcc-lib/i386-redhat-linux/egcs-2.91.66/include/stdarg.h
readfile.o: /usr/include/bits/types.h /usr/include/libio.h
readfile.o: /usr/include/_G_config.h /usr/include/bits/stdio_lim.h
readfile.o: /usr/include/X11/Xlib.h /usr/include/sys/types.h
readfile.o: /usr/include/time.h /usr/include/endian.h
readfile.o: /usr/include/bits/endian.h /usr/include/sys/select.h
readfile.o: /usr/include/bits/select.h /usr/include/bits/sigset.h
readfile.o: /usr/include/sys/sysmacros.h /usr/include/X11/X.h
readfile.o: /usr/include/X11/Xfuncproto.h /usr/include/X11/Xosdefs.h
readfile.o: /usr/include/X11/Xutil.h vroot.h /usr/include/X11/Xatom.h
readfile.o: /usr/include/sys/ipc.h /usr/include/bits/ipc.h
readfile.o: /usr/include/sys/shm.h /usr/include/unistd.h
readfile.o: /usr/include/bits/posix_opt.h /usr/include/bits/confname.h
readfile.o: /usr/include/getopt.h /usr/include/bits/shm.h
readfile.o: /usr/include/X11/extensions/XShm.h proto.h /usr/include/stdlib.h
readfile.o: /usr/include/alloca.h /usr/include/signal.h
readfile.o: /usr/include/bits/signum.h /usr/include/bits/siginfo.h
readfile.o: /usr/include/bits/sigaction.h /usr/include/bits/sigcontext.h
readfile.o: /usr/include/asm/sigcontext.h /usr/include/bits/sigstack.h
readfile.o: /usr/include/netinet/in.h /usr/include/stdint.h
readfile.o: /usr/include/bits/socket.h /usr/include/bits/sockaddr.h
readfile.o: /usr/include/asm/socket.h /usr/include/asm/sockios.h
readfile.o: /usr/include/bits/in.h /usr/include/bits/byteswap.h util.h
readfile.o: dither.h /usr/include/string.h
floatdct.o: /usr/include/math.h /usr/include/features.h
floatdct.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
floatdct.o: /usr/include/bits/huge_val.h /usr/include/bits/mathdef.h
floatdct.o: /usr/include/bits/mathcalls.h
floatdct.o: /usr/lib/gcc-lib/i386-redhat-linux/egcs-2.91.66/include/float.h
ctrlbar.o: /usr/include/stdio.h /usr/include/features.h
ctrlbar.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
ctrlbar.o: /usr/lib/gcc-lib/i386-redhat-linux/egcs-2.91.66/include/stddef.h
ctrlbar.o: /usr/lib/gcc-lib/i386-redhat-linux/egcs-2.91.66/include/stdarg.h
ctrlbar.o: /usr/include/bits/types.h /usr/include/libio.h
ctrlbar.o: /usr/include/_G_config.h /usr/include/bits/stdio_lim.h
ctrlbar.o: /usr/include/stdlib.h /usr/include/sys/types.h /usr/include/time.h
ctrlbar.o: /usr/include/endian.h /usr/include/bits/endian.h
ctrlbar.o: /usr/include/sys/select.h /usr/include/bits/select.h
ctrlbar.o: /usr/include/bits/sigset.h /usr/include/sys/sysmacros.h
ctrlbar.o: /usr/include/alloca.h /usr/include/string.h dither.h video.h
ctrlbar.o: /usr/include/X11/Xlib.h /usr/include/X11/X.h
ctrlbar.o: /usr/include/X11/Xfuncproto.h /usr/include/X11/Xosdefs.h
ctrlbar.o: /usr/include/X11/Xutil.h vroot.h /usr/include/X11/Xatom.h
ctrlbar.o: /usr/include/sys/ipc.h /usr/include/bits/ipc.h
ctrlbar.o: /usr/include/sys/shm.h /usr/include/unistd.h
ctrlbar.o: /usr/include/bits/posix_opt.h /usr/include/bits/confname.h
ctrlbar.o: /usr/include/getopt.h /usr/include/bits/shm.h
ctrlbar.o: /usr/include/X11/extensions/XShm.h ctrlbar.h proto.h
ctrlbar.o: /usr/include/sys/time.h /usr/include/bits/time.h
