.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH ANIM-FLAME 1 "June 27, 2001"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
anim-flame \- part of electricsheep, frame renderer
.SH SYNOPSIS
.B anim-flame
.RI [ options ]
.SH DESCRIPTION
This program is a part of the 
.B electricsheep(1)
package and should not be used stand-alone.
.B electricsheep(1)
uses this program to render frames for the animation.
.SH OPTIONS
This program takes arguments from
.B electricsheep(1)
.SH AUTHOR
This manual page was written by Sander Smeenk <ssmeenk@debian.org>,
for the Debian GNU/Linux system (but may be used by others).
