.TH FLAM3-CONVERT 1 "June 17, 2005"
.SH NAME
flam3-convert \- fractal converter for electricsheep(1)
.SH DESCRIPTION
flam3-convert comes with the electricsheep(1) package.
It reads from stdin the old format created by
the GIMP and writes to stdout the new xml format.
.SH OPTIONS
This program gets its opions through environment variables.
See flam3-convert -h for details.
.br
.SH AUTHOR
This manual page was written by Alexis Sukrieh <sukria@sukria.net> 
for the Debian GNU/Linux system (but may be used by others).
