.TH FLAM3-ANIMATE 1 "June 17, 2005"
.SH NAME
flam3-animate \- makes animation from .flam3 files
.SH DESCRIPTION
flam3-animate comes with the electricsheep(1) package.
It can make animations from .flam3 files.
.SH OPTIONS
This program gets its opions through environment variables.
See flam3-animate -h for details.
.br
.SH AUTHOR
This manual page was written by Alexis Sukrieh <sukria@sukria.net> 
for the Debian GNU/Linux system (but may be used by others).
