.TH FLAM3-RENDER 1 "June 17, 2005"
.SH NAME
flam3-render \- renderer of .flam3 files
.SH DESCRIPTION
flam3-render comes with the electricsheep(1) package.
It takes a .flam3 file on stdin and renders it.
.SH OPTIONS
This program gets its opions through environment variables.
See flam3-render -h for details.
.br
.SH AUTHOR
This manual page was written by Alexis Sukrieh <sukria@sukria.net> 
for the Debian GNU/Linux system (but may be used by others).
