.TH FLAM3-GENOME 1 "June 17, 2005"
.SH NAME
flam3-genome \- fractal parameters generator for electricsheep(1)
.SH DESCRIPTION
flam3-genome comes with the electricsheep(1) package.
It creates random parameter files. it also mutates,
rotates, and interpolates existing parameter files. 
.SH OPTIONS
This program gets its opions through environment variables.
See flam3-genome -h for details.
.br
.SH AUTHOR
This manual page was written by Alexis Sukrieh <sukria@sukria.net> 
for the Debian GNU/Linux system (but may be used by others).
